package com.iamincendium.spacetraders.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
public data class FactionTrait(
    @SerialName("symbol") val symbol: Symbol,
    @SerialName("name") val name: String,
    @SerialName("description") val description: String,
) {
    @Serializable
    public enum class Symbol {
        @SerialName("BUREAUCRATIC") BUREAUCRATIC,
        @SerialName("SECRETIVE") SECRETIVE,
        @SerialName("CAPITALISTIC") CAPITALISTIC,
        @SerialName("INDUSTRIOUS") INDUSTRIOUS,
        @SerialName("PEACEFUL") PEACEFUL,
        @SerialName("DISTRUSTFUL") DISTRUSTFUL,
        @SerialName("WELCOMING") WELCOMING,
        @SerialName("SMUGGLERS") SMUGGLERS,
        @SerialName("SCAVENGERS") SCAVENGERS,
        @SerialName("REBELLIOUS") REBELLIOUS,
        @SerialName("EXILES") EXILES,
        @SerialName("PIRATES") PIRATES,
        @SerialName("RAIDERS") RAIDERS,
        @SerialName("CLAN") CLAN,
        @SerialName("GUILD") GUILD,
        @SerialName("DOMINION") DOMINION,
        @SerialName("FRINGE") FRINGE,
        @SerialName("FORSAKEN") FORSAKEN,
        @SerialName("ISOLATED") ISOLATED,
        @SerialName("LOCALIZED") LOCALIZED,
        @SerialName("ESTABLISHED") ESTABLISHED,
        @SerialName("NOTABLE") NOTABLE,
        @SerialName("DOMINANT") DOMINANT,
        @SerialName("INESCAPABLE") INESCAPABLE,
        @SerialName("INNOVATIVE") INNOVATIVE,
        @SerialName("BOLD") BOLD,
        @SerialName("VISIONARY") VISIONARY,
        @SerialName("CURIOUS") CURIOUS,
        @SerialName("DARING") DARING,
        @SerialName("EXPLORATORY") EXPLORATORY,
        @SerialName("RESOURCEFUL") RESOURCEFUL,
        @SerialName("FLEXIBLE") FLEXIBLE,
        @SerialName("COOPERATIVE") COOPERATIVE,
        @SerialName("UNITED") UNITED,
        @SerialName("STRATEGIC") STRATEGIC,
        @SerialName("INTELLIGENT") INTELLIGENT,
        @SerialName("RESEARCH_FOCUSED") RESEARCH_FOCUSED,
        @SerialName("COLLABORATIVE") COLLABORATIVE,
        @SerialName("PROGRESSIVE") PROGRESSIVE,
        @SerialName("MILITARISTIC") MILITARISTIC,
        @SerialName("TECHNOLOGICALLY_ADVANCED") TECHNOLOGICALLY_ADVANCED,
        @SerialName("AGGRESSIVE") AGGRESSIVE,
        @SerialName("IMPERIALISTIC") IMPERIALISTIC,
        @SerialName("TREASURE_HUNTERS") TREASURE_HUNTERS,
        @SerialName("DEXTEROUS") DEXTEROUS,
        @SerialName("UNPREDICTABLE") UNPREDICTABLE,
        @SerialName("BRUTAL") BRUTAL,
        @SerialName("FLEETING") FLEETING,
        @SerialName("ADAPTABLE") ADAPTABLE,
        @SerialName("SELF_SUFFICIENT") SELF_SUFFICIENT,
        @SerialName("DEFENSIVE") DEFENSIVE,
        @SerialName("PROUD") PROUD,
        @SerialName("DIVERSE") DIVERSE,
        @SerialName("INDEPENDENT") INDEPENDENT,
        @SerialName("SELF_INTERESTED") SELF_INTERESTED,
        @SerialName("FRAGMENTED") FRAGMENTED,
        @SerialName("COMMERCIAL") COMMERCIAL,
        @SerialName("FREE_MARKETS") FREE_MARKETS,
        @SerialName("ENTREPRENEURIAL") ENTREPRENEURIAL,
    }
}
